/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@interface SFDAffineGeometry : NSObject <NSCopying>
{
    struct _NSSize mNaturalSize;
    struct _NSSize mSize;
    BOOL mSizesLocked;
    BOOL mAspectRatioLocked;
    struct _NSPoint mPosition;
    float mAngle;
    BOOL mHorizontalFlip;
    BOOL mVerticalFlip;
    float mShearXAngle;
    float mShearYAngle;
    NSAffineTransform *mCachedTransform;
}

+ (void)initialize;
+ (id)properties;
- (id)initWithNaturalSize:(struct _NSSize)fp8 size:(struct _NSSize)fp16 sizesLocked:(BOOL)fp24 aspectRatioLocked:(BOOL)fp28 position:(struct _NSPoint)fp32 angleInDegrees:(float)fp40 horizontalFlip:(BOOL)fp44 verticalFlip:(BOOL)fp48 shearXAngle:(float)fp52 shearYAngle:(float)fp56;
- (id)initWithNaturalSize:(struct _NSSize)fp8 size:(struct _NSSize)fp16 sizesLocked:(BOOL)fp24 aspectRatioLocked:(BOOL)fp28 position:(struct _NSPoint)fp32 angleInDegrees:(float)fp40 horizontalFlip:(BOOL)fp44 verticalFlip:(BOOL)fp48;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (BOOL)isEqual:(id)fp8;
- (unsigned int)hash;
- (id)description;
- (void)setGeometry:(id)fp8;
- (struct _NSSize)naturalSize;
- (void)setNaturalSize:(struct _NSSize)fp8;
- (struct _NSSize)size;
- (void)setSize:(struct _NSSize)fp8;
- (BOOL)sizesLocked;
- (void)setSizesLocked:(BOOL)fp8;
- (BOOL)aspectRatioLocked;
- (void)setAspectRatioLocked:(BOOL)fp8;
- (struct _NSPoint)position;
- (void)setPosition:(struct _NSPoint)fp8;
- (float)angleInDegrees;
- (void)setAngleInDegrees:(float)fp8;
- (void)setAngleAboutCenterInDegrees:(float)fp8;
- (float)angleInRadians;
- (void)setAngleInRadians:(float)fp8;
- (BOOL)horizontalFlip;
- (void)setHorizontalFlip:(BOOL)fp8;
- (BOOL)verticalFlip;
- (void)setVerticalFlip:(BOOL)fp8;
- (float)shearXAngle;
- (void)setShearXAngle:(float)fp8;
- (float)shearYAngle;
- (void)setShearYAngle:(float)fp8;
- (struct _NSRect)naturalBounds;
- (struct _NSRect)bounds;
- (struct _NSPoint)naturalCenter;
- (struct _NSPoint)center;
- (id)transform;
- (id)scaleTransform;
- (id)compareProperties:(id)fp8;
- (BOOL)differOnlyByTranslation:(id)fp8;
- (BOOL)intersectsGeometry:(id)fp8;
- (void)translateNaturalPoint:(struct _NSPoint)fp8 toPoint:(struct _NSPoint)fp16 makePositionIntegral:(BOOL)fp24;
- (void)translateNaturalPoint:(struct _NSPoint)fp8 toPoint:(struct _NSPoint)fp16;
- (void)transformBy:(id)fp8 rotateBy:(float)fp12 horizontalFlip:(BOOL)fp16 verticalFlip:(BOOL)fp20;
- (void)transformByWithAngleAndFlipFixed:(id)fp8;
- (id)geometryRelativeToGeometry:(id)fp8;
- (void)appendGeometry:(id)fp8;
- (void)scaleBy:(double)fp8 withOffset:(struct _NSPoint)fp16;
- (void)scaleXBy:(double)fp8 yBy:(double)fp16;

@end

