/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

#import "SFRSubviewAbsolverView.h"

@class CIContext, SFRBitmapRenderingQualityInfo, SFRLabel, SFUMutablePointerSet, SFXSessionContext;

struct _CGLayerInfo {
    unsigned int layerInfoVersion;
    struct _CGLayerInfo *next;
    void *fetchTile;
    unsigned int layerInfo;
    void *colorData;
    void *alphaData;
    void *customData;
    int colorBytesPerRow;
    int alphaBytesPerRow;
    int clipMinX;
    int clipMaxX;
    int clipMinY;
    int clipMaxY;
    int frameMinX;
    int frameMaxX;
    int frameMinY;
    int frameMaxY;
    int opaqueMinX;
    int opaqueMaxX;
    int opaqueMinY;
    int opaqueMaxY;
    int bitmapType;
    unsigned int constantColor;
    unsigned int layerData;
    float fade;
    void *texture;
    unsigned int *stamp;
    void *clipShape;
    void *opaqueShape;
    float texMinX;
    float texMaxX;
    float texMinY;
    float texMaxY;
    unsigned int flags;
    void *link;
    float brightness;
    void *filters;
    unsigned int reserved[4];
};

@interface SFRCanvas : SFRSubviewAbsolverView
{
    SFXSessionContext *mSession;
    float _scale;
    int _destination;
    BOOL _usesCompositor;
    struct _CGLayerInfo _backgroundLayer;
    NSColor *_backgroundColor;
    BOOL mRenderBlackAndWhite;
    BOOL mIsStatic;
    int mBitmapImageQuality;
    int mChartQuality;
    SFRBitmapRenderingQualityInfo *mBitmapRenderingQualityInfo;
    BOOL mAccelerated;
    NSOpenGLContext *mOpenGLContext;
    NSImage *mMinimizedImage;
    struct _CGDirectDisplayID *mDisplayID;
    struct __CVDisplayLink *mDisplayLink;
    NSRecursiveLock *mDisplayLinkLock;
    BOOL mDeallocating;
    SFUMutablePointerSet *mRegisteredRenderables;
    CIContext *mCIContext;
    NSTimer *mFPSTimer;
    NSDate *mFPSDate;
    int mFrameCount;
    SFRLabel *mFPSRenderable;
}

- (BOOL)isFlipped;
- (BOOL)scaleShadowsWhenZooming;
- (void)setBackgroundColor:(id)fp8;
- (id)backgroundColor;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)registerRenderable:(id)fp8;
- (void)unregisterRenderable:(id)fp8;
- (void)dealloc;
- (void)setScale:(float)fp8;
- (void)setScale:(float)fp8 scrollingToMaintainCenter:(BOOL)fp12;
- (float)viewScale;
- (float)viewScaleWithoutUserSpaceScale;
- (BOOL)isOpaque;
- (BOOL)isStatic;
- (void)setIsStatic:(BOOL)fp8;
- (int)bitmapImageQuality;
- (void)setBitmapImageQuality:(int)fp8;
- (int)chartQuality;
- (void)setChartQuality:(int)fp8;
- (id)bitmapRenderingQualityInfo;
- (void)setUsesCompositor:(BOOL)fp8;
- (BOOL)usesCompositor;
- (void)setRenderingDestination:(int)fp8;
- (int)renderingDestination;
- (void)setRendersBlackAndWhite:(BOOL)fp8;
- (BOOL)rendersBlackAndWhite;
- (id)additionalShadowTransform;
- (id)objectsToRender;
- (void)drawRect:(struct _NSRect)fp8;
- (void)compositeRect:(struct _NSRect)fp8;

@end

