/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>
#import "SFRCanvas.h"

@class NSArray, NSValue, SFDDrawableRep, SFDEditablePathController, SFDGuideController, SFDPDFHyperlinkController, SFDRulerLineRep, SFDSelectionController, SFDToolController, SFWPHyperlinkField;

@interface SFDCanvas : SFRCanvas <NSTextInput> {
    SFDSelectionController *mSelectionController;
    SFDToolController *mToolController;
    SFDGuideController *mGuideController;
    BOOL mMouseIsDown;
    BOOL mMouseIsDragging;
    NSValue *mMarquee;
    NSArray *mDynamicGuides;
    BOOL mIsInteractive;
    SFDDrawableRep *mEditingRep;
    SFDDrawableRep *mRepToHighlight;
    struct _NSPoint mRepHighlightLocation;
    BOOL mClipContentsToPage;
    BOOL mShowsLayoutMarks;
    BOOL mShowsHyperlinkBadges;
    BOOL mShowsGuides;
    int mBorderDrawingMethod;
    SFDRulerLineRep *mRulerLine;
    BOOL mSupportsMotionPaths;
    SFDEditablePathController *mActivePathController;
    SFWPHyperlinkField *mRolloverHyperlinkField;
    SFDPDFHyperlinkController *mHyperlinkController;
}

+ (id)imageDataOfType:(id)fp8 forDrawable:(id)fp12 returnSize:(struct _NSSize *)fp16 returnLocation:(struct _NSPoint *)fp20;
+ (id)imageDataOfType:(id)fp8 forDrawables:(id)fp12;
+ (id)imageDataOfType:(id)fp8 forDrawables:(id)fp12 onCanvas:(id)fp16;
+ (id)imageDataOfType:(id)fp8 forReps:(id)fp12 onCanvas:(id)fp16;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (void)awakeFromNib;
- (void)invalidateCursorRect;
- (id)toolController;
- (id)selectionController;
- (id)guideController;
- (id)contents;
- (id)pageContainingPoint:(struct _NSPoint)fp8;
- (id)pagesInRect:(struct _NSRect)fp8;
- (id)visiblePages;
- (BOOL)shouldClipContentsToPage;
- (void)setShouldClipContentsToPage:(BOOL)fp8;
- (void)setRepToHighlight:(id)fp8 atLocation:(struct _NSPoint)fp12;
- (id)repToHighlight;
- (id)dataManager;
- (void)beginEditingRep:(id)fp8 withEvent:(id)fp12;
- (void)setActivePathController:(id)fp8;
- (id)activePathController;
- (void)setEditingRep:(id)fp8;
- (id)editingRep;
- (void)endEditing;
- (void)endEditingWithoutChangingFirstResponder;
- (id)associatedRepsForRep:(id)fp8;
- (void)mouseMoved:(id)fp8;
- (BOOL)mouseIsDown;
- (BOOL)resignFirstResponder;
- (struct _NSPoint)boundaryConstrainedOffsetForMovingObjects:(id)fp8 byOffset:(struct _NSPoint)fp12;
- (void)didConstrainMovementOfMovingObjects:(id)fp8;
- (void)willBeginMovementOfObjects:(id)fp8;
- (void)didEndMovementOfObjects:(id)fp8;
- (void)mouseDown:(id)fp8;
- (void)keyDown:(id)fp8;
- (void)flagsChanged:(id)fp8;
- (void)resetCursorRects;
- (BOOL)supportsMotionPaths;
- (void)setSupportsMotionPaths:(BOOL)fp8;
- (id)objectsToRender;
- (id)repForInfo:(id)fp8;
- (BOOL)subclassWillFlush;
- (void)addHyperlinkForRect:(struct _NSRect)fp8 withUrl:(id)fp24;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)willDrawHandles;
- (void)drawBorders;
- (void)drawSelectedRepHandles;
- (void)drawSelectedRepBezierHandles;
- (void)setMarquee:(id)fp8;
- (id)marquee;
- (id)dynamicGuidesForNonSelectedDrawables;
- (id)dynamicGuidesForActivePage;
- (id)provideGuides;
- (id)provideStaticGuides;
- (id)provideNewGuide;
- (id)staticGuidesForPage:(id)fp8;
- (void)setDynamicGuides:(id)fp8;
- (BOOL)showsLayoutMarks;
- (void)setShowsLayoutMarks:(BOOL)fp8;
- (void)setShowsHyperlinkBadges:(BOOL)fp8;
- (BOOL)showsHyperlinkBadges;
- (BOOL)isValidHyperlink:(id)fp8 forDrawable:(id)fp12;
- (void)setRolloverHyperlinkField:(id)fp8;
- (void)drawHyperlinkBadges;
- (int)borderDrawingMethod;
- (void)setBorderDrawingMethod:(int)fp8;
- (BOOL)showsGuides;
- (void)setShowsGuides:(BOOL)fp8;
- (void)selectionChanged;
- (void)didDeselectAll;
- (void)updateRulerlinesWithOldRect:(struct _NSRect)fp8 newRect:(struct _NSRect)fp24;
- (void)eraseRulerlines;
- (BOOL)isInteractive;
- (void)setIsInteractive:(BOOL)fp8;
- (id)menuForEvent:(id)fp8;
- (void)updateRulerLineForRuler:(id)fp8 to:(float)fp12;
- (void)insertText:(id)fp8;
- (id)attributedSubstringFromRange:(struct _NSRange)fp8;
- (unsigned int)characterIndexForPoint:(struct _NSPoint)fp8;
- (long)conversationIdentifier;
- (void)doCommandBySelector:(SEL)fp8;
- (struct _NSRect)firstRectForCharacterRange:(struct _NSRange)fp8;
- (BOOL)hasMarkedText;
- (struct _NSRange)markedRange;
- (struct _NSRange)selectedRange;
- (void)setMarkedText:(id)fp8 selectedRange:(struct _NSRange)fp12;
- (void)unmarkText;
- (id)validAttributesForMarkedText;

@end

