/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@interface SFRSubviewAbsolverView : NSView
{
    struct _NSRect mDisplayRect;
    NSView *mVisibleView;
    BOOL mIsVisibleRect;
    BOOL mDrawsOwnSubviews;
    SEL mEntryPoint;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (BOOL)drawsOwnSubviews;
- (void)setDrawsOwnSubviews:(BOOL)fp8;
- (void)clearSubviewCache;
- (void)_recursiveDisplayAllDirtyWithLockFocus:(BOOL)fp8 visRect:(struct _NSRect)fp12;
- (void)_recursiveDisplayRectIfNeededIgnoringOpacity:(struct _NSRect)fp8 isVisibleRect:(BOOL)fp24 rectIsVisibleRectForView:(id)fp28 topView:(BOOL)fp32;
- (BOOL)drawSubview:(id)fp8;

@end

